package tests;

import base.BaseTest;
import io.restassured.response.Response;
import org.testng.annotations.Test;
import static io.restassured.RestAssured.*;
import org.testng.Assert;
@org.testng.annotations.Listeners(reports.ExtentReportManager.class)


public class UserTest extends BaseTest //Inheritance (using extends BaseTest) 
{

	@Test
	public void testCRUDFlow() {
		// These logs will appear as 'Steps' in your HTML dashboard
		reports.ExtentReportManager.logStep("Step 1: Generating dynamic payload using Java Faker");
	    // 1. Prepare the Dynamic Data (Encapsulation)
		// Why: We don't hardcode data in the test. We ask a specialized class (Payload)
	    // to give us a fresh Java Object. This keeps the test clean
		pojo.User requestPayload = payload.UserPayload.createUser();

		// 2. THE ACTION (Abstraction)
	    // Why: The test shouldn't care about URLs or Headers. It just tells the 
	    // 'UserEndpoints' worker to "go create this". This is the Service Layer pattern.
		 reports.ExtentReportManager.logStep("Step 2: Sending POST request to create a new user");
        Response res = utils.UserEndpoints.createUser(requestPayload);
     // 3. EXTRACTION (Correlation/Chaining)
        // Why: In real-world APIs, we must capture the ID generated by the DB 
        // to perform follow-up actions (Update/Delete) on that specific record. 
        // Extract the ID as a String from the JSON response
        reports.ExtentReportManager.logStep("Step 3: Extracting the user ID from the response");
	    String myId = res.jsonPath().getString("id");

	    //System.out.println("The ID created by the server is: " + myId);


	    // 3. Convert Response back to POJO (Deserialization)
	    // JSON -> Java Object
	    //GET (We call the Worker again!)
//	    Response getRes = utils.UserEndpoints.getUser(myId);
	 // Change this temporarily just to see the names match on this fake API
	    reports.ExtentReportManager.logStep("Step 4: Performing GET request to verify data for ID: " + myId);
	    Response getRes = utils.UserEndpoints.getUser("1"); 

	 // 4. DESERIALIZATION (JSON to POJO Mapping)
	    // Why: Comparing raw JSON strings is hard. Converting JSON back to a Java Object 
	    // allows us to use standard Java methods (like .name) to verify data accurately.
	 pojo.User responsePayload = res.as(pojo.User.class); 

	// 5. VALIDATION (The "Heart" of Testing)
	    // Why: A test without assertions is just a script. 
	    // We verify the Status Code (is the API up?) and the Data (is the API correct?).
	 reports.ExtentReportManager.logStep("Step 5: Validating Status Code and Data Integrity");
	    Assert.assertEquals(res.getStatusCode(), 201, "Status code mismatch!");
	    
	 // 6. Extracting the ID:  Use the extracted ID to fetch the record (Chaining)
	    System.out.println("Step 5: Verifying the record with GET request for ID: " + myId);
	    
	    // Verify the name and job match exactly what we generated via Faker
	    Assert.assertEquals(responsePayload.name, requestPayload.name, "Name does not match!");
	    Assert.assertEquals(responsePayload.job, requestPayload.job, "Job does not match!");

	    System.out.println("Assertion Passed: Response name '" + responsePayload.name + 
	                       "' matches Request name '" + requestPayload.name + "'");
	}
    @Test
    public void testUserNotFound() {
        System.out.println("Step 6: Negative Testing - Requesting a non-existent ID");
        
        given()
            .spec(requestSpec)
        .when()
            .get("/posts/999999") // This ID definitely does not exist
        .then()
            .log().status()
            .statusCode(404); // We EXPECT a 404 Not Found
            
        System.out.println("Negative Test Passed: API correctly returned 404 for invalid ID.");
    }
 // CI/CD Mastery Complete!
	

    }

